### ISSUE TITLE
断点续传

### ISSUE THREAD

**Issue by yikeruguo** [xugai/FILESTORE-SERVER#1]
我最近也在学这门课，百度云盘的课程，少了两节讲断点续传的，在你这里找到了。你是买了这门课的吗？断点续传你是只完成了上传部分吗?下载时的断点续传完成没？

**Comment by xugai** [comment]
哈哈你好同学。对的，我也是买了这门课程的，原视频里少了两节的断点续传，我自己靠自己的理解给补上来了。你可以看看，另外呢，下载的断点续传还没写。我是先跟着课程的进度来写的。

**Comment by yolo-pd** [comment]
我没买，网上找的资源，少了两节，我以为你们买了的是完整的，没想到也是坑。你还没学完吗？是准备拆分成微服务？go-micro更新太频繁了，感觉有点乱来的，api老是改
